- name: "Check and validate"
  section: "Validation"
  tasks:
    - name: Check, tag, and confirm documents
      section: Check, tag, and confirm documents
      tasks:
        - name: Review documents
        - name: Check and request documents
    - name: Check application details
      section: Check application details
      tasks:
        - name: Draw red line boundary
          hidden: true
        - name: Check red line boundary
        - name: Check constraints
        - name: Check description
        - name: Check fee
        - name: Add reporting details
    - name: Confirm application requirements
      section: Confirm application requirements
      tasks:
        - name: Confirm Community Infrastructure Levy (CIL)
        - name: Check Environment Impact Assessment
        - name: Check ownership certificate
    - name: Other validation issues
      section: Other validation issues
      tasks:
        - name: Other validation requests
- name: "Consultees, neighbours and publicity"
  section: "Consultation"
- name: "Check and assess"
  section: "Assessment"
  tasks:
    - name: Check application
      section: Check application
      tasks:
        - name: Check consultees
- name: "View recommendation"
  section: "Review"
- name: "Publish determination"
  section: "Review"
