- name: "Check and validate"
  section: "Validation"
- name: "Consultees"
  section: "Consultation"
- name: "Check and assess"
  section: "Assessment"
  tasks:
    - name: Check application
      section: Check application
      tasks:
        - name: Check application details
          legacy_url: ""
        - name: Check consultees consulted
          legacy_url: ""
        - name: Check site history
          legacy_url: ""
    - name: Additional services
      section: Additional services
      tasks:
        - name: Site visit
          legacy_url: ""
        - name: Meeting
          legacy_url: ""
    - name: Assessment summaries
      section: Assessment summaries
      tasks:
        - name: Site description
          legacy_url: ""
        - name: Planning considerations and advice
          legacy_url: ""
        - name: Suggest heads of terms
          legacy_url: ""
        - name: Summary of advice
          legacy_url: ""
    - name: Complete assessment
      section: Complete assessment
      tasks:
        - name: Choose application type
          legacy_url: ""
        - name: Check and add requirements
          legacy_url: ""
        - name: Review and submit pre-application
          legacy_url: submit_recommendation_planning_application
- name: "View recommendation"
  section: "Review"
