- name: "Check and validate"
  section: "Validation"
  tasks:
    - name: Check, tag, and confirm documents
      section: Check, tag, and confirm documents
      tasks:
        - name: Review documents
        - name: Check and request documents
    - name: Check application details
      section: Check application details
      tasks:
        - name: Draw red line boundary
          hidden: true
        - name: Check red line boundary
        - name: Check constraints
        - name: Check description
        - name: Check requested services
        - name: Check fee
    - name: Other validation issues
      section: Other validation issues
      tasks:
        - name: Other validation requests
    - name: Review
      section: Review
      tasks:
        - name: Review validation requests
          status_hidden: true
        - name: Send validation decision
- name: "Consultees"
  section: "Consultation"
  tasks:
    - name: Determine consultation requirement
    - name: Add and assign consultees
      hidden: true
    - name: Send emails to consultees
      hidden: true
    - name: View consultee responses
      hidden: true
- name: "Check and assess"
  section: "Assessment"
  tasks:
    - name: Check application
      section: Check application
      tasks:
        - name: Check application details
          legacy_url: ""
        - name: Check consultees
          legacy_url: ""
        - name: Check site history
          legacy_url: ""
    - name: Additional services
      section: Additional services
      tasks:
        - name: Site visit
          legacy_url: ""
        - name: Meeting
          legacy_url: ""
    - name: Assessment summaries
      section: Assessment summaries
      tasks:
        - name: Site and surroundings
          legacy_url: ""
        - name: Planning considerations and advice
          legacy_url: ""
        - name: Suggest heads of terms
          legacy_url: ""
        - name: Summary of advice
          legacy_url: ""
    - name: Complete assessment
      section: Complete assessment
      tasks:
        - name: Choose application type
          legacy_url: ""
        - name: Check and add requirements
          legacy_url: ""
        - name: Review and submit pre-application
          legacy_url: ""
- name: "View recommendation"
  section: "Review"
