name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-name: "staging"
    secrets: inherit

  deploy-prod:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-name: "production"
    secrets: inherit
