---
name: Deploy to pentest

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to pentest
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-name: "pentest"
    secrets: inherit
