name: Tag release
on:
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types: ["completed"]
jobs:
  tag-release:
    name: Tag release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +%Y-%m-%dT%H.%M)" >>$GITHUB_OUTPUT

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: release-${{ steps.date.outputs.date }}
          tag_prefix: ""

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          prerelease: true
          makeLatest: false
          token: ${{ secrets.DEPLOY_TOKEN }}
